version: '3.8'

services:
  hardhat:
    build:
      dockerfile: docker/hardhat/Dockerfile
      context: .
    environment:
      - MNEMONIC
      - FORK_URL_BSC
      - FORK_CHAIN_ID=56
      - FORK_BLOCK_NUMBER
    ports:
      - "8545:8545"
#    volumes:
#      - ./packages/sdk/deployments/localhost:/tmp/build/packages/sdk/deployments/localhost
  liquidator-bot:
    build:
      dockerfile: docker/liquidator/Dockerfile
      context: .
    env_file:
      - docker/liquidator/liquidator.env
    environment:
      - ETHEREUM_ADMIN_ACCOUNT
      - ETHEREUM_ADMIN_PRIVATE_KEY
      - WEB3_HTTP_PROVIDER_URL=http://hardhat:8545
    entrypoint: "/bin/sh -c './wait-for-hh.sh && pm2-runtime ecosystem.config.js --env production'"
    restart: always

  twap-bot:
    build:
      dockerfile: docker/twap/Dockerfile
      context: .
    depends_on:
      - hardhat
    env_file:
      - docker/twap/twap.env
    environment:
      - ETHEREUM_ADMIN_ACCOUNT
      - ETHEREUM_ADMIN_PRIVATE_KEY
      - WEB3_HTTP_PROVIDER_URL=http://hardhat:8545
    entrypoint: "/bin/sh -c './wait-for-hh.sh && pm2-runtime ecosystem.config.js --env production'"
    restart: always
