[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
base = "./"
publish = "./packages/ui/.next"
command = "yarn build:deploy:ui"

[build.environment]
YARN_CHECKSUM_BEHAVIOR = "update"

[context.branch-deploy.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "true"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
ICON_SERVER="https://d1912tcoux65lj.cloudfront.net"
FEATURE_RSS="false"

[context.production.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "false"
EVMOS = "false"
BSC = "true"
MOONBEAM = "false"
ICON_SERVER="https://d1912tcoux65lj.cloudfront.net"
FEATURE_RSS="false"
