[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
base = "./"
publish = "./packages/ui/.next"
command = "yarn build:deploy:ui"

[build.environment]
YARN_CHECKSUM_BEHAVIOR = "update"
SUPABASE_URL="https://xdjnvsfkwtkwfuayzmtm.supabase.co"
ICON_SERVER="https://d1912tcoux65lj.cloudfront.net"
PRODUCT_URL='https://app.midascapital.xyz'
FEATURE_CREATE_POOL="0x27521eae4eE4153214CaDc3eCD703b9B0326C908,0x2680D8f1ED3BEe1c731cFeedcDa2A74bB7317828,0x7dB8d33114462e032E5bf636D271f8680619Ba25"
FEATURE_DEPLOY_FLYWHEEL="false"

[context.preview.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "true"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "true"
FANTOM = "true"
ETHEREUM = "true"
IS_SENTRY_ENABLED = "false"

[context.development.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "true"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "true"
FANTOM = "true"
ETHEREUM = "true"
IS_SENTRY_ENABLED = "false"

[context.production.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "false"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "false"
FANTOM = "true"
IS_SENTRY_ENABLED = "true"

[functions]
directory = "./packages/functions/dist/functions/src/functions"
node_bundler = "esbuild"

[functions."plugin-rewards-*"]
schedule = "@hourly"

[functions."asset-apys-*"]
schedule = "@hourly"

[functions."vault-data-*"]
schedule = "@hourly"
