[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
base = "./"
publish = "./packages/ui/.next"
command = "yarn build:deploy:ui"

[build.environment]
YARN_CHECKSUM_BEHAVIOR = "update"
SUPABASE_URL="https://xdjnvsfkwtkwfuayzmtm.supabase.co"
ICON_SERVER="https://d1912tcoux65lj.cloudfront.net"
PRODUCT_URL='https://app.midascapital.xyz'
FEATURE_CREATE_POOL="0x82eDcFe00bd0ce1f3aB968aF09d04266Bc092e0E,0x2680D8f1ED3BEe1c731cFeedcDa2A74bB7317828"

[context.preview.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "true"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "true"
FANTOM = "true"

[context.development.environment]
NEXTAUTH_URL="https://development.midascapital.xyz"
NEXT_PUBLIC_SHOW_TESTNETS = "true"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "true"
FANTOM = "true"

[context.production.environment]
NEXTAUTH_URL="https://app.midascapital.xyz"
NEXT_PUBLIC_SHOW_TESTNETS = "false"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "false"
FANTOM = "false"

[functions]
directory = "./packages/functions/dist/functions/src/functions"
node_bundler = "esbuild"

[functions."plugin-rewards-*"]
schedule = "@hourly"

[functions."asset-apys-*"]
schedule = "@hourly"
