[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
base = "./"
publish = "./packages/ui/.next"
command = "yarn build:deploy:ui"

[build.environment]
YARN_CHECKSUM_BEHAVIOR = "update"
SUPABASE_URL="https://xdjnvsfkwtkwfuayzmtm.supabase.co"
SUPABASE_PLUGIN_TABLE_NAME="apy-plugin"
SUPABASE_FLYWHEEL_TABLE_NAME="apy-flywheel"
SUPABASE_NATIVE_PRICES_TABLE_NAME="native-prices"
ICON_SERVER="https://d1912tcoux65lj.cloudfront.net"

[context.branch-deploy.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "true"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "true"
FEATURE_RSS="false"
FEATURE_CREATE_POOL="0x82eDcFe00bd0ce1f3aB968aF09d04266Bc092e0E"
HIDE_POOLS_56="2,4,5"
HIDE_POOLS_97="2,6,11,17,20,21,22,23"

[context.production.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "false"
EVMOS = "false"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "false"
FEATURE_RSS="false"
FEATURE_CREATE_POOL="0x304aE8f9300e09c8B33bb1a8AE1c14A6253a5F4D"
HIDE_POOLS_56="2,4,5"
HIDE_POOLS_97="2,6,11,17,20,21,22,23"
FUNCTIONS_ALERT_WEBHOOK_URL='https://discord.com/api/webhooks/1009764740186259456/DPvitzelL3UNrxh13plhIXqW__XyFtQix_i_103XMM7UtnjtsW6I1RjnfbLMIFlcM0QS'

[functions]
directory = "./packages/functions/dist/functions/src/functions"
node_bundler = "esbuild"

[functions."bsc-save-price"]
schedule = "@hourly"

[functions."moonbeam-save-price"]
schedule = "@hourly"

[functions."polygon-save-price"]
schedule = "@hourly"

# [functions."save-native-prices"]
# # Every 5 Minutes
# schedule = "*/5 * * * *"
