[[plugins]]
  package = "@netlify/plugin-nextjs"


[build]
  base    = "/"
  command = "yarn build:deploy:ui"
  publish = "/packages/ui/.next"

[build.environment]
  NEXT_PUBLIC_SHOW_TESTNETS = "true"
  YARN_CHECKSUM_BEHAVIOR = "update"