[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
base = "./"
publish = "./packages/ui/.next"
command = "yarn build:deploy:ui"

[build.environment]
YARN_CHECKSUM_BEHAVIOR = "update"
SUPABASE_URL="https://xdjnvsfkwtkwfuayzmtm.supabase.co"
ICON_SERVER="https://d1912tcoux65lj.cloudfront.net"
PRODUCT_URL='https://app.midascapital.xyz'
HIDE_POOLS_56="2,4,5"
HIDE_POOLS_97="2,6,11,17,20,21,22,23"
HIDE_POOLS_137="4"
FEATURE_CREATE_POOL="0x82eDcFe00bd0ce1f3aB968aF09d04266Bc092e0E"

[context.preview.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "true"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "true"

[context.development.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "true"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "true"

[context.production.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "false"
EVMOS = "false"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ARBITRUM = "false"

[functions]
directory = "./packages/functions/dist/functions/src/functions"
node_bundler = "esbuild"

[functions."bsc-save-price"]
schedule = "@hourly"

[functions."moonbeam-save-price"]
schedule = "@hourly"

[functions."polygon-save-price"]
schedule = "@hourly"
