[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
base = "./"
publish = "./packages/ui/.next"
command = "yarn build:deploy:ui"

[build.environment]
YARN_CHECKSUM_BEHAVIOR = "update"
SUPABASE_URL="https://xdjnvsfkwtkwfuayzmtm.supabase.co"
SUPABASE_PLUGIN_TABLE_NAME="apy-plugin"
SUPABASE_FLYWHEEL_TABLE_NAME="apy-flywheel"

[context.branch-deploy.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "true"
EVMOS = "true"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ICON_SERVER="https://d1912tcoux65lj.cloudfront.net"
FEATURE_RSS="false"
FEATURE_CREATE_POOL="0x304aE8f9300e09c8B33bb1a8AE1c14A6253a5F4D"
MIN_BORROW_USD="100"
HIDE_ASSETS="0x8f552a71EFE5eeFc207Bf75485b356A0b3f01eC9,0x6Ba38f006aFe746B9A0d465e53aB4182147AC3D7"
HIDE_POOLS="{'56':'2,4,5','97':'2,6,11,17,20,21,22,23'}"

[context.production.environment]
NEXT_PUBLIC_SHOW_TESTNETS = "false"
EVMOS = "false"
BSC = "true"
MOONBEAM = "true"
POLYGON = "true"
ICON_SERVER="https://d1912tcoux65lj.cloudfront.net"
FEATURE_RSS="false"
FEATURE_CREATE_POOL="0x304aE8f9300e09c8B33bb1a8AE1c14A6253a5F4D"
MIN_BORROW_USD="100"
HIDE_ASSETS="0x8f552a71EFE5eeFc207Bf75485b356A0b3f01eC9,0x6Ba38f006aFe746B9A0d465e53aB4182147AC3D7"
HIDE_POOLS="{'56':'2,4,5','97':'2,6,11,17,20,21,22,23'}"

[functions]
directory = "./packages/functions/netlify/functions"
node_bundler = "esbuild"

[functions."bsc-save-price"]
schedule = "@hourly"

[functions."moonbeam-save-price"]
schedule = "@hourly"
