name: SDK/Push/PR - build and run tests

on:
  push:
    branches:
      - main
      - development
    paths:
      - "packages/sdk/**"
      - "yarn.lock"
  pull_request:
    branches:
      - main
      - development
    paths:
      - "packages/sdk/**"
      - "yarn.lock"

jobs:
  build-and-test-local:
    env:
      MNEMONIC: "${{ secrets.MNEMONIC }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: "${{ secrets.ACCESS_TOKEN }}"

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install NPM packages
        run: yarn install
        env:
          # Fixes issue: `ethereumjs-abi: The remote archive doesn't match the expected checksum`
          YARN_CHECKSUM_BEHAVIOR: update

      - name: Update forge deps
        run: yarn workspace @midas-capital/sdk forge update

      - name: Run build
        run: yarn workspace @midas-capital/sdk build

      - name: Run hardhat tests
        run: yarn workspace @midas-capital/sdk test

  build-and-test-bsc:
    env:
      MNEMONIC: "${{ secrets.MNEMONIC }}"
      FORK_URL_BSC: "${{ secrets.FORK_URL_BSC }}"
      FORK_BLOCK_NUMBER: 17366495
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: "${{ secrets.ACCESS_TOKEN }}"

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      # Not needed as we checkout recursively
      # Does not work yet, no access to `contracts` repo
      # - name: forge module install
      #   run: yarn workspace @midas-capital/sdk forge install

      - name: Install `packages`
        run: yarn install
        env:
          # Fixes issue: `ethereumjs-abi: The remote archive doesn't match the expected checksum`
          YARN_CHECKSUM_BEHAVIOR: update

      - name: Run build
        run: yarn workspace @midas-capital/sdk build

      - name: Run hardhat tests on BSC
        run: yarn workspace @midas-capital/sdk test:bsc
