name: SDK/Push - Publish

on:
  push:
    branches:
      - main
    paths:
      - "packages/sdk/**"
      - "yarn.lock"
jobs:
  build-and-test-local:
    env:
      MNEMONIC: "${{ secrets.MNEMONIC }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.3.0
        with:
          name: Install Forge dependencies
          cmd: workspace @midas-capital/sdk forge install

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: workspace @midas-capital/sdk build

      - name: Run build
        run: npm run build

      - uses: borales/actions-yarn@v2.3.0
        with:
          name: Run hardhat tests
          cmd: workspace @midas-capital/sdk test:hardhat

  release:
    needs:
      - build-and-test-local
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      MNEMONIC: "${{ secrets.MNEMONIC }}"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.3.0
        with:
          name: Install Forge dependencies
          cmd: workspace @midas-capital/sdk forge install

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: workspace @midas-capital/sdk build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{env.GITHUB_REF_NAME == 'main' && 'latest' || 'beta'}}
          access: "public"
