name: UI/PR - build and test

on:
  pull_request:
    branches: [main, staging, development]
    paths:
      - "packages/ui/**"
      - "yarn.lock"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: "${{ secrets.ACCESS_TOKEN }}"

      - name: Install `foundry`
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install `foundry libs`
        run: yarn workspace @midas-capital/sdk foundry install

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Clear `yarn` Cache
        run: yarn cache clean

      - name: Install `packages`
        run: yarn install

      - name: Lint `ui`
        run: yarn workspace @midas-capital/ui lint

      - name: Build `sdk`
        run: yarn workspace @midas-capital/sdk build

      - name: Build `ui`
        run: yarn workspace @midas-capital/ui build
