name: SDK/Push/PR - build and run tests

on:
  push:
    branches:
      - main
      - development
    paths:
      - "packages/sdk/**"
  pull_request:
    branches:
      - main
      - development
    paths:
      - "packages/sdk/**"

jobs:
  build-and-test-local:
    env:
      MNEMONIC: "${{ secrets.MNEMONIC }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: "${{ secrets.ACCESS_TOKEN }}"

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install NPM packages
        run: yarn

      - name: forge module install
        run: yarn workspace @midas-capital/sdk forge install

      - name: Run build
        run: yarn workspace @midas-capital/sdk build

      - name: Run hardhat tests
        run: yarn workspace @midas-capital/sdk test

  build-and-test-bsc:
    env:
      MNEMONIC: "${{ secrets.MNEMONIC }}"
      FORK_URL_BSC: "${{ secrets.FORK_URL_BSC }}"
      FORK_BLOCK_NUMBER: 17366495
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.ACCESS_TOKEN }}"

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Forge dependencies
        run: forge install

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install NPM packages
        run: yarn

      - name: forge module install
        run: yarn workspace @midas-capital/sdk forge install

      - name: Run build
        run: yarn workspace @midas-capital/sdk build

      - name: Run hardhat tests on BSC
        run: yarn workspace @midas-capital/sdk test:bsc
