name: UI/PR - build and test

on:
  pull_request:
    branches: [main, staging, development]
    paths:
      - "packages/ui/**"
      - "yarn.lock"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn workspace @midas-capital/ui lint
      - name: Build
        run: yarn workspace @midas-capital/ui build
