name: SDK/Push/PR - build and run tests

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'packages/sdk/**'
      - 'packages/chains/**'
      - 'packages/types/**'
      - '.github/workflows/package-sdk-pull-request-build-and-test.yml'
      - 'yarn.lock'
  pull_request:
    branches:
      - main
      - development
    paths:
      - 'packages/sdk/**'
      - 'packages/chains/**'
      - 'packages/types/**'
      - '.github/workflows/package-sdk-pull-request-build-and-test.yml'
      - 'yarn.lock'

jobs:
  build-lint-and-test-local:
    env:
      MNEMONIC: '${{ secrets.MNEMONIC }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: '${{ secrets.ACCESS_TOKEN }}'

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install NPM packages
        run: yarn install
        env:
          # Fixes issue: `ethereumjs-abi: The remote archive doesn't match the expected checksum`
          YARN_CHECKSUM_BEHAVIOR: update

      - name: Checkout correct submodule contents
        run: yarn checkout:lib

      - name: Build SDK
        run: yarn build:sdk

      - name: Run lint
        run: yarn workspace @midas-capital/sdk lint

      - name: Run mocha tests
        run: yarn workspace @midas-capital/sdk test:mocha

      - name: Run hardhat tests
        run: yarn workspace @midas-capital/sdk test

  build-and-test-bsc:
    env:
      MNEMONIC: '${{ secrets.MNEMONIC }}'
      FORK_URL_BSC: '${{ secrets.FORK_URL_BSC }}'
      FORK_BLOCK_NUMBER: 19279700
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: '${{ secrets.ACCESS_TOKEN }}'

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install `packages`
        run: yarn install
        env:
          # Fixes issue: `ethereumjs-abi: The remote archive doesn't match the expected checksum`
          YARN_CHECKSUM_BEHAVIOR: update

      - name: Checkout correct submodule contents
        run: yarn checkout:lib

      - name: Build SDK
        run: yarn build:sdk

      - name: Run lint
        run: yarn workspace @midas-capital/sdk lint

      - name: Run hardhat tests on BSC
        run: yarn workspace @midas-capital/sdk test:bsc
